### ISSUE TITLE
Stereochemistry of Phytanic Acid Metabolism

### ISSUE THREAD

**Issue by Devlin-Moyer** [SysBioChalmers/Human-GEM#773]
### Current behavior:

Human-GEM's representation of the stereochemistry of phytanic acid metabolites is inconsistent: some metabolites clearly specifically represent the (3S) enantiomers, while others seem to represent racemic mixtures of the (3S) and (3R) enantiomers:

Metabolite/Reaction | unspecified/racemic version | S enantiomer
---|---|---
phytanic acid | `MAM02746` | doesn't exist
phytanoyl-CoA | `MAM02747` | `MAM03362`
2-hydroxyphytanoyl-CoA | `MAM00655` | `MAM03363`
pristanal | doesn't exist | `MAM00564`
pristanic acid | `MAM02766` | doesn't exist
pristanoyl-CoA | `MAM03884` | `MAM00078`
phytanic acid [c] -> phytanoyl-CoA [c] | `MAR03480` | `MAR03388`
phytanic acid [c] -> phytanic acid [x] | `MAR03478` | doesn't exist
phytanoyl-CoA [c] -> phytanoyl-CoA [x] | `MAR06779` and `MAR03481` | doesn't exist
phytanic acid [x] -> phytanoyl-CoA [x] | `MAR03482` | `MAR03389`
phytanoyl-CoA [x] -> 2-hydroxyphytanoyl-CoA [x] | `MAR03484` | `MAR03384`
2-hydroxyphytanoyl-CoA [x] -> pristanal [x] | `MAR03486` | `MAR03385`
pristanal [x] -> pristanic acid [x] | `MAR03386` | doesn't exist
pristanic acid [x] -> pristanoyl-CoA [x] | `MAR05183` | `MAR03387`

### Expected feature/value/output:

Apparently, most people's diets contain both (3S) and (3R)-phytanic acid, and while the enzymes responsible for the alpha-oxidation of phytanic acid (i.e. the enzymes responsible for the reactions mentioned in this issue) work with either enantiomer, the enzymes responsible for the beta-oxidation of pristanoyl-CoA only recognize (2S)-pristanoyl-CoA, so people who are born with defective [AMACR](https://www.uniprot.org/uniprotkb/Q9UHK6/entry) (the enzyme responsible for converting (2R)-pristanoyl-CoA into (2S)-pristanoyl-CoA) can only fully metabolize (3S)-phytanic acid and accumulate (2R)-pristanic acid in their blood ([source](https://doi.org/10.1016/S0022-2275(20)30150-4)). In order to properly reflect this, I think the unspecified/racemic phytanic acid metabolites should be edited to instead represent the (3R)-enantiomers, and the reactions involving these two sets of metabolites should be fully separated from each other up until `MAR03491`, which already represents the isomerization of (2R)-pristanoyl-CoA and (2S)-pristanoyl-CoA by AMACR:

Metabolite/Reaction | (S) version | (R) version
---|---|---
phytanic acid | `MAM03884` | `MAM02746`
phytanoyl-CoA | `MAM03362` | `MAM02747`
2-hydroxyphytanoyl-CoA | `MAM03363` | `MAM00655`
pristanal | `MAM00564` | need to make a new one
pristanic acid | `MAM02766` | `MAM00077`
pristanoyl-CoA | `MAM00078` | `MAM00075`
<-> phytanic acid [e] | `MAR00659` | `MAR09037`
phytanic acid [e] -> phytanic acid [c] | `MAR01617` | `MAR00440`
phytanic acid [c] -> phytanoyl-CoA [c] | `MAR03388` | `MAR03480`
phytanoyl-CoA [c] -> phytanoyl-CoA [x] | `MAR06779` | `MAR03481`
phytanic acid [x] -> phytanoyl-CoA [x] | `MAR03389` | `MAR03482`
phytanoyl-CoA [x] -> 2-hydroxyphytanoyl-CoA [x] | `MAR03384` | `MAR03484`
2-hydroxyphytanoyl-CoA [x] -> pristanal [x] | `MAR03385` | `MAR03486`
pristanal [x] -> pristanic acid [x] | `MAR03386` | `MAR03488`
pristanic acid [x] -> pristanoyl-CoA [x] | `MAR03387` | `MAR03493`

I noticed that #646 removed the `MAM03884` metabolites and all associated reactions for being duplicates of the `MAM02746` metabolites, since both sets represent(ed) phytanic acid. I'm proposing to bring back the `MAM03884` metabolites and reactions so that they can represent (3R)-phytanic acid, so that we can edit the `MAM02746` metabolites and reactions to specifically represent (3S)-phytanic acid.

`MAR03481` and `MAR06779` both represent transport of phytanoyl-CoA from the cytosol into peroxisomes, but only `MAR06779` correctly represents that this is an ATP-dependent process mediated by [ABCD3](https://www.uniprot.org/uniprotkb/P28288/entry) ([source](https://doi.org/10.1016/j.bbalip.2013.12.001)). Since they both use the racemic phytanoyl-CoA metabolite (`MAM02747`), and there is no equivalent reaction using (2S)-phytanoyl-CoA (`MAM03362`), I'm proposing to edit both reactions so that they both represent ATP-dependent import, but one uses (2S)-phytanoyl-CoA and the other uses (2R)-phytanoyl-CoA. Also it turns out that ABCD3 probably removes the CoA from its substrates just before it transports them across the peroxisomal membrane ([source](https://doi.org/10.1038/s41598-021-81949-3)), so I'm also accounting for that in my proposed changes.

### Proposed changes:

- [x] Rename `MAM02746e`, `MAM02746c` and `MAM02746x` to "(3R)-phytanic acid"
- [x] Bring back `MAM03884e`, `MAM03884c` and `MAM03884x` and rename them to "(3S)-phytanic acid"
- [x] Bring back `MAR00659` and `MAR01617` (exchange and [e] <-> [c] transport reactions for `MAM03884`)
- [x] Rename `MAM02747c` and `MAM02747x` to "(3R)-phytanoyl-CoA"
- [x] Replace `MAM02746c` with `MAM03884c` in `MAR03388`
- [x] Edit `MAR03481` to be `MAM02747c + MAM01371c + 2 MAM02040c -> MAM02746x + MAM01597c + MAM02039c + MAM01285c + MAM02751c`, GPR: `ENSG00000117528`, references: `PMID:24333844;PMID:33500543`
- [x] Edit `MAR06779` to be `MAM03362c + MAM01371c + 2 MAM02040c -> MAM03384x + MAM01597c + MAM02039c + MAM01285c + MAM02751c`, GPR: `ENSG00000117528`, references: `PMID:24333844;PMID:33500543`
- [x] Replace `MAM02746x` with `MAM03884x` in `MAR03389`
- [x] Rename `MAM00655x` to "(3R)-2-hydroxyphytanoyl-CoA"
- [x] Create a new metabolite to represent peroxisomal (2R)-pristanal
- [x] Replace (2S)-pristanal (`MAM00564x`) with the new (2R)-pristanal metabolite in `MAR03486`
- [x] Rename `MAM02766e`, `MAM02766c`, and `MAM02766x` to "(2S)-pristanic acid"
- [x] Bring back `MAR03488` and `MAM00077x`, but replace `MAM00564x` with the new (2R)-pristanal metabolite in `MAR03488`
- [x] Replace `MAM02766x` with `MAM00077x` in `MAR03493`
- [x] Create `MAM00077c` and `MAM00077e` to represent cytosolic and extracellular (2R)-pristanic acid
- [x] Replace `MAM02766c` with `MAM00077c` in `MAR03390`
- [x] Create new reactions like `MAR11966` and `MAR11967` but with `MAM00077c` and `MAM000077e` instead of `MAM02766c` and `MAM02766e`

These changes don't address the existence of Pristanoyl Coenzyme A (`MAM03887`) in addition to (2S)-pristanoyl-CoA (`MAM00078`) and (2R)-pristanoyl-CoA (`MAM00075`); that's taken care of in #776

**Comment by haowang-bioinfo** [comment]
> 3(S)-Phytanoyl-CoA (MAM03362c and MAM03362x) and 3(S)-2-Hydroxyphytanoyl-CoA (MAM03363x) seem to be entirely redundant with phytanoyl-CoA (MAM02747c and MAM02747x) and 2-hydroxyphytanoyl-CoA (MAM00655x)

@Devlin-Moyer if you have more evidence demonstrating that 3(S)-Phytanoyl-CoA (MAM03362c and MAM03362x) and 3(S)-2-Hydroxyphytanoyl-CoA (MAM03363x) are the same?

@Christoff1993 if you can help to double check this?

**Comment by Devlin-Moyer** [comment]
sorry I may not have written that super clearly; 3(S)-Phytanoyl-CoA (`MAM03362`) is the same as phytanoyl-CoA (`MAM02747`), and 3(S)-2-Hydroxyphytanoyl-CoA (`MAM03363`) is the same as 2-hydroxyphytanoyl-CoA (`MAM00655`)

**Comment by Devlin-Moyer** [comment]
I just came across [this paper](https://doi.org/10.1016/S0022-2275(20)30150-4) that mentions that people's diets usually consist of a racemic mixture of (3S)- and (3R)-phytanic acid, and while the enzymes responsible for the alpha-oxidation of phytanic acid to pristanal recognize either enantiomer, ACOX2 and ACOX3 (the enzymes responsible for the first step of beta-oxidation of pristanic acid) only act on 2S-pristanoyl-CoA, so people born with defective AMACR (the enzyme responsible for converting 2R-pristanoyl-CoA into 2S-pristanoyl-CoA) accumulate 2R-pristanic acid in their blood.

At the moment, it seems like `MAM02746`, `MAM02747`, and `MAM00655x` represent racemic phtyanic acid, phytanoyl-CoA, and 2-hydroxyphytanoyl-CoA, and no metabolites that are currently present in Human-GEM specifically represent the 3R enantiomers. The stereochemistry gets even more confusing with the metabolites representing pristanal, pristanic acid, and pristanoyl-CoA; 2S-pristanal (`MAM00564x`) becomes (racemic?) pristanic acid (`MAM02766x`) in `MAR03386`, which can become 2S-pristanoyl-CoA (`MAM00078x`) in `MAR03387`, 2R-pristanoyl-CoA (`MAM00075x`) in `MAR03493`, or (racemic?) pristanoyl-CoA (`MAM03887x`) in `MAR05183`. The changes I proposed in the initial comment would basically remove any semblance of stereospecificity in this pathway; if we instead wanted to represent each enantiomer with a separate metabolite, we should instead:

- [ ] Rename `MAM02746e`, `MAM02746c` and `MAM02746x` to "(3R)-phytanic acid"
- [ ] Rename `MAM02747c` and `MAM02747x` to "(3R)-phytanoyl-CoA"
- [ ] Rename `MAM00655x` to "(3R)-2-hydroxyphytanoyl-CoA"
- [ ] Create a new metabolite to represent peroxisomal (2R)-pristanal
- [ ] Replace (2S)-pristanal (`MAM00564x`) with the new (2R)-pristanal metabolite in `MAR03486`
- [ ] Bring back (2R,6S,10S)-pristanate (`MAM00077x`), `MAR03488`, and `MAR03489` (they were removed in #519)
- [ ] Replace (2S)-pristanal (`MAM00564x`) with the new (2R)-pristanal metabolite in `MAR03488`
- [ ] Replace (2S)-pristanoyl-CoA (`MAM00078x`) with (2R)-pristanoyl-CoA (`MAM00075x`) in `MAR03489`
- [ ] Create new metabolites for extracellular and cytosolic (3S)-phytanic acid as well as an exchange reaction and [e] <-> [c] transport reaction
- [ ] Replace `MAM02746c` with the new cytosolic (3S)-phytanic acid metabolite in `MAR03388`
- [ ] Create a new [c] <-> [x] transport reaction for the existing (3S)-phytanoyl-CoA metabolites (`MAM03362`)
- [ ] Keep `MAM03362c`, `MAM03362x`, `MAM03363x`, `MAR03384`, and `MAR03385` exactly as they are (i.e. instead of removing them, as initially proposed in this issue)
- [ ] Remove `MAR03389` (currently converts phytanic acid (`MAM02746x`) to 3S-phytanoyl-CoA (`MAM03362x`); `MAR03482` converts phytanic acid (`MAM02746x`) to phytanoyl-CoA (`MAM02747x`), so if we rename both of those to (3R)-phytanic acid and (3R)-phytanoyl-CoA, we only want to keep `MAR03482`)
- [ ] Remove `MAR05186` and `MAR05187` (I already proposed this in #775 since they duplicate `MAR03486` + `MAR03386` in addition to being ambiguous about stereochemistry)
- [ ] Remove pristanoyl-CoA (`MAM03887x`), `MAR05183`, `MAR05184`, and `MAR01600` (I already proposed this in #776 before being aware of the stereochemistry situation)

This would create two fully distinct series of metabolites and reactions for representing each pair of enantiomers that converge at `MAR03491`, which already interconverts (2R)-pristanoyl-CoA (`MAM00075x`) and (2S)-pristanoyl-CoA (`MAM00078x`):

Reaction | ID using S-enantiomers | ID using R-enantiomers
---|---|---
Exchange of phytanic acid | new | `MAR09037`
Transport of phytanic acid from [e] to [c] | new | `MAR00440`
Transport of phytanic acid from [c] to [x] | not sure if necessary | `MAR03478`
Phytanic acid to phytanoyl-CoA in [c] | `MAR03388` | `MAR06779`
Transport of phytanoyl-CoA from [c] to [x] | new | `MAR03481`
Phytanic acid to phytanoyl-CoA in [x] | not sure if necessary | `MAR03482`
Phytanoyl-CoA to 2-hydroxyphytanoyl-CoA | `MAR03384` | `MAR03484`
2-hydroxyphytanoyl-CoA to pristanal | `MAR03385` | `MAR03486`
Pristanal to pristanic acid | `MAR03386` | `MAR03488`
Pristanic acid to pristanoyl-CoA | `MAR03387` | `MAR03489`

Metabolite | S-enantiomer | R-enantiomer
---|---|---
Phytanic acid | new | `MAM02746`
Phytanoyl-CoA | `MAM03362` | `MAM02747`
2-Hydroxyphytanoyl-CoA | `MAM03363` | `MAM00655`
Pristanal | `MAM00564` | new
Pristanic acid | `MAM02766` | `MAM00077`
Pristanoyl-CoA | `MAM00078` | `MAM00075`

**Comment by Devlin-Moyer** [comment]
I edited the proposed changes to try and accurately reflect the stereochemistry that's relevant to these reactions

**Comment by Christoff1993** [comment]
I have checked the reasoning and citations, and everything seems comprehensive and sound: all the indicated ambiguities do indeed exist and the proposed changes will solve them. I have no disagreements/additional suggestions.
